### ISSUE TITLE
Sensors Unknown

### ISSUE THREAD

**Issue by jenshorn** [vinnyspb/esphome-comfortzone#16]
First of all, thanks for a great integration! Very easy to set up and get started with EX50 in HA.

Now, most of the sensors appears to work great but there are a few that are constantly _Unknown_. Is this something you have experienced as well? Perhaps it's an issue for the [decoder library](https://github.com/qix67/comfortzone_heatpump)?
- Extra hot water setting
- Fan speed
- Heating CoP
- Hot water priority setting

Hot Water CoP are mostly _Unknown_ but receives data occasionally?
<img width="410" alt="image" src="https://github.com/vinnyspb/esphome-comfortzone/assets/1868780/6d6598f8-da13-4364-855f-e6fb9ddb8165">

Running [commit 1ff3b41 on main](https://github.com/vinnyspb/esphome-comfortzone/commit/1ff3b41d4df38141826f7ce602dfb272a72fd44a), protocol 1.80.

**Comment by vinnyspb** [comment]
Hi @jenshorn,

Heating CoP is calculated only when actual heating takes place, which I'd assume happens rarely at the moment due to summer time. You should see more consistent values during the winter season.

Other values from your list are decoded incorrectly in the upstream library as you correctly mentioned. I haven't had time to debug it unfortunately.
